# VO + API + Profile
vo=gpu-next
gpu-api=d3d11
profile=high-quality

# Hardware Decoding
hwdec=auto-safe

# Scaling
scale=lanczos
cscale=lanczos

# Temporal Scaling
video-sync=display-resample
interpolation=yes
tscale=oversample

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=no
screenshot-directory="C:\Users\joao\Pictures\mpvshots"
screenshot-template="%F-%wH_%wM_%wS_%#02n"

# Misc
no-hidpi-window-scale
alang=jpn,en
slang=en

# Meme shaders
glsl-shader="~~/shaders/cfl_prediction_12tap.glsl"

[bench]
audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
d3d11-sync-interval=0
osd-msg1="FPS: ${estimated-display-fps}"