# VO + hwdec
vo=gpu-next
hwdec=auto-safe

# Scaling
dscale=lanczos
linear-downscaling=no

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=no
screenshot-dir="~/Pictures/mpvshots"
screenshot-template="%F-%wH_%wM_%wS_%#02n"

# Misc
no-hidpi-window-scale
dither-depth=8
audio-channels=stereo
alang=jpn,en
slang=en

# Profiles
[QHD-]
profile-desc=QHD-
profile-cond=width < 2560
cscale=bilinear
glsl-shader="~~/shaders/ArtCNN_C4F16_DS_YCbCr.glsl"

[bench]
audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
d3d11-sync-interval=0
osd-msg1="FPS: ${estimated-display-fps}"
