# VO + API
vo=gpu-next
gpu-api=d3d11

# Hardware Decoding
hwdec=auto-safe

# Scaling
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=ewa_robidoux
dscale-param1=0
dscale-param2=0

correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

# Temporal Scaling
video-sync=display-resample
interpolation=yes
tscale=oversample

# Debanding and Dithering
dither-depth=8
deband=yes

# HDR autism
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=no
screenshot-directory="C:\Users\joao\Pictures\mpvshots"
screenshot-template="%F-%wH_%wM_%wS_%#02n"

# Misc
no-hidpi-window-scale
alang=jpn,en
slang=en

[bench]
audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
d3d11-sync-interval=0
osd-msg1="FPS: ${estimated-display-fps}"